In [1]:
import pandas as pd
import numpy as np


In [2]:
messages = pd.read_csv("SpamClassifier-master/SMSSpamCollection.txt",sep="\t",names=["label","massage"])

In [3]:
messages.head()

label                                            massage
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
import re
from nltk.corpus import stopwords


In [5]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [6]:
corpus = []

for i in range(0,len(messages)):
    review = re.sub("^a-zA-Z"," ",messages["massage"][i])  # here if the word does not contain alphabets from a to z OR A to Z just remove that word (Special charecter detection)
    review = review.lower()
    review = review.split()
    review =[ps.stem(word) for word in review if word not in set(stopwords.words("english"))]
    review = " ".join(review)
    corpus.append(review)


In [7]:
corpus

['go jurong point, crazy.. avail bugi n great world la e buffet... cine got amor wat...',
 'ok lar... joke wif u oni...',
 "free entri 2 wkli comp win fa cup final tkt 21st may 2005. text fa 87121 receiv entri question(std txt rate)t&c' appli 08452810075over18'",
 'u dun say earli hor... u c alreadi say...',
 'nah think goe usf, live around though',
 "freemsg hey darl 3 week' word back! like fun still? tb ok! xxx std chg send, £1.50 rcv",
 'even brother like speak me. treat like aid patent.',
 "per request 'mell mell (oru minnaminungint nurungu vettam)' set callertun callers. press *9 copi friend callertun",
 'winner!! valu network custom select receivea £900 prize reward! claim call 09061701461. claim code kl341. valid 12 hour only.',
 'mobil 11 month more? u r entitl updat latest colour mobil camera free! call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight, k? cri enough today.',
 'six chanc win cash! 100 20,000 pound txt> csh11 send 87575. cost 15

# Create Bag Of Words

In [8]:
## Creating the Bag of word model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv = CountVectorizer(max_features=500,binary=True)

In [9]:
X = cv.fit_transform(corpus).toarray()

In [10]:
print(X.shape)

(5572, 500)


In [11]:
cv.vocabulary_ ## here we can get the top 500 Most reapeted words from Dataset

{'go': 163,
 'great': 171,
 'world': 482,
 'got': 169,
 'wat': 460,
 'ok': 302,
 'lar': 224,
 'wif': 471,
 'free': 151,
 'entri': 136,
 'win': 474,
 'final': 144,
 'may': 258,
 'text': 411,
 'receiv': 352,
 'question': 343,
 'txt': 444,
 'rate': 345,
 'dun': 126,
 'say': 368,
 'earli': 128,
 'alreadi': 28,
 'think': 419,
 'goe': 165,
 'live': 240,
 'around': 39,
 'though': 421,
 'hey': 193,
 'week': 463,
 'word': 480,
 'back': 46,
 'like': 237,
 'fun': 157,
 'still': 402,
 'xxx': 488,
 'send': 375,
 '50': 12,
 'even': 138,
 'brother': 62,
 'speak': 398,
 'me': 260,
 'per': 319,
 'set': 378,
 'friend': 152,
 'network': 284,
 'custom': 99,
 'select': 374,
 'prize': 338,
 'claim': 83,
 'call': 69,
 'code': 87,
 'valid': 451,
 'hour': 200,
 'only': 307,
 'mobil': 271,
 'month': 273,
 'latest': 228,
 'colour': 89,
 'camera': 71,
 'co': 86,
 'gonna': 167,
 'home': 197,
 'soon': 394,
 'want': 459,
 'talk': 408,
 'stuff': 404,
 'tonight': 432,
 'enough': 134,
 'today': 427,
 'chanc': 78,
 'cas

In [12]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

# Using the N-Grams Parameter

In [13]:
## Creating the Bag of word model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv = CountVectorizer(max_features=500,binary=True,ngram_range=(1,2))
X = cv.fit_transform(corpus).toarray()

In [14]:
cv.vocabulary_

{'go': 159,
 'great': 168,
 'world': 484,
 'got': 167,
 'wat': 462,
 'ok': 302,
 'lar': 222,
 'wif': 473,
 'free': 146,
 'entri': 131,
 'win': 476,
 'final': 139,
 'may': 258,
 'text': 414,
 'receiv': 354,
 'question': 345,
 'txt': 446,
 'rate': 347,
 'dun': 122,
 'say': 369,
 'earli': 124,
 'alreadi': 26,
 'think': 422,
 'goe': 161,
 'live': 239,
 'around': 37,
 'though': 424,
 'hey': 191,
 'week': 465,
 'word': 482,
 'back': 44,
 'like': 236,
 'fun': 153,
 'still': 404,
 'xxx': 489,
 'send': 376,
 '50': 13,
 'even': 132,
 'brother': 58,
 'speak': 400,
 'me': 260,
 'per': 319,
 'set': 380,
 'friend': 148,
 'network': 284,
 'custom': 95,
 'select': 374,
 'prize': 340,
 'claim': 79,
 'call': 64,
 'code': 84,
 'valid': 453,
 'hour': 198,
 'only': 308,
 'mobil': 271,
 'month': 273,
 'latest': 226,
 'colour': 86,
 'camera': 67,
 'co': 82,
 'free call': 147,
 'gonna': 163,
 'home': 195,
 'soon': 395,
 'want': 461,
 'talk': 411,
 'stuff': 406,
 'tonight': 434,
 'enough': 129,
 'today': 430,


In [15]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

# Create TF-IDF And NGrams

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(corpus).toarray()

In [18]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

In [21]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.404, 0, 0.471, 0.555, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.555, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.458, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0.47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.488, 0, 0, 0, 0, 0, 0, 0, 0.576, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],

## Word2Vec Implementation

In [ ]:
import gensim.downloader as api
wv = api.load("word2vec-google-news-300")

vec_king = wv["king"]

In [ ]:
vec_king

In [ ]:
vec_king.shape